Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 2
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	6	verify_vars
	7
Select jobs to execute...

[Thu Dec  3 10:18:18 2020]
rule verify_vars:
    input: data/remapped_vars/ENSSSCG00000000922.remapped
    output: data/verified_vars/ENSSSCG00000000922.verified
    jobid: 313
    wildcards: id=ENSSSCG00000000922

[Thu Dec  3 10:18:18 2020]
rule verify_vars:
    input: data/remapped_vars/ENSSSCG00000024497.remapped
    output: data/verified_vars/ENSSSCG00000024497.verified
    jobid: 385
    wildcards: id=ENSSSCG00000024497

[Thu Dec  3 10:21:36 2020]
Finished job 385.
1 of 7 steps (14%) done
[Thu Dec  3 10:50:24 2020]
Finished job 313.
2 of 7 steps (29%) done
Select jobs to execute...

[Thu Dec  3 10:50:24 2020]
rule verify_vars:
    input: data/remapped_vars/ENSSSCG00000002756.remapped
    output: data/verified_vars/ENSSSCG00000002756.verified
    jobid: 354
    wildcards: id=ENSSSCG00000002756

[Thu Dec  3 10:50:24 2020]
rule verify_vars:
    input: data/remapped_vars/ENSSSCG00000008088.remapped
    output: data/verified_vars/ENSSSCG00000008088.verified
    jobid: 333
    wildcards: id=ENSSSCG00000008088

[Thu Dec  3 10:50:26 2020]
Error in rule verify_vars:
    jobid: 333
    output: data/verified_vars/ENSSSCG00000008088.verified

RuleException:
CalledProcessError in line 41 of /home/pelmo/sscrofa_variant_remapping/Snakefile:
Command 'set -euo pipefail;  /home/pelmo/anaconda3/envs/snakemake/bin/python3.9 /home/pelmo/sscrofa_variant_remapping/.snakemake/scripts/tmpx391i8pb.var_confirmation.py' returned non-zero exit status 1.
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2273, in run_wrapper
  File "/home/pelmo/sscrofa_variant_remapping/Snakefile", line 41, in __rule_verify_vars
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2304, in run_wrapper
Terminating processes on user request, this might take some time.
[Thu Dec  3 10:59:04 2020]
Error in rule verify_vars:
    jobid: 354
    output: data/verified_vars/ENSSSCG00000002756.verified

RuleException:
CalledProcessError in line 41 of /home/pelmo/sscrofa_variant_remapping/Snakefile:
Command 'set -euo pipefail;  /home/pelmo/anaconda3/envs/snakemake/bin/python3.9 /home/pelmo/sscrofa_variant_remapping/.snakemake/scripts/tmpueq5tvh4.var_confirmation.py' died with <Signals.SIGINT: 2>.
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2273, in run_wrapper
  File "/home/pelmo/sscrofa_variant_remapping/Snakefile", line 41, in __rule_verify_vars
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2304, in run_wrapper
Complete log: /home/pelmo/sscrofa_variant_remapping/.snakemake/log/2020-12-03T101818.633510.snakemake.log
